### ISSUE TITLE
AP11 stuff ready for the web site

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl-website#10]
If I did it all correctly, you should find in the boards src folder new files for:

bd02 v6.3
bd03 v6.3
bd71 v6.0
bd72 v6.0
bd73 v6.0
ovrOB
ovrSt
ovrX

These need to be added to vasl.info so everyone can play all the scenarios in AP11.
Bd02 and 03 add lightwoods transformations.

I did not update the master board version text file because I thought with the auto map download feature of VASL 6.3.1 players would be told they were using an old board until the new boards get added to the site. When these boards get uploaded, if someone would be kind enough to update the version text file with the versions noted above, I'd appreciate it greatly.

I hope I did this all correct. If not, please school me :-)

Thanks!

Edit: ovrOB is brand new overlay category

**Comment by davidsullivan317** [comment]
Thanks so much for doing this Al. You should be okay updating the board version file but you just need to add the new/updated boards to the boards repository.

**Comment by BigAl737** [comment]
David, sorry for this noob question...when you say boards repository, do you mean the boards folder that is within the vasl-website (here: https://github.com/vasl-developers/vasl-website/tree/master/boards )?

If I do that does that update the website so that the boards are available to the public on vasl.info?

I certainly do not want to tread where I shouldn't so am proceeding cautiously here.

**Comment by BigAl737** [comment]
A lot of work did go into this release but it wasn't just me. Scott Hasson, our new board cabaler did bds 71 and 73. And although not part of this release, Brian Kemp did bds 69 and 70. Brian's also already completed all the boards for the upcoming PiF release by BFP. You've got time to do the transforms now, eh Brian :-)

There's one more cabaler warming up in the bull pen too...Ken Knott. Although Ken hasn't pitched a board yet, he has been instrumental in the latest effort to get MMP to agree to providing raw files for our use.

There's one more that's interested too. Erwin Langlois from Belgium. He's been working in solitary converting CH boards. I'll bring him on shortly.

It seems as if Tom Sayer was right, it's a lot of fun white washing this old fence :-)

**Comment by zgrose** [comment]
I don't see any files committed to any of the folders. Did you push your changes in git? We won't see anything in GitHub until you commit and push the changes.

**Comment by BigAl737** [comment]
I did push them. They went to the vasl boards repository here:

https://github.com/vasl-developers/vasl/tree/develop/boards/src

**Comment by zgrose** [comment]
Excellent, I see them now. So they just need to be zipped up (compiled into a board, so to speak, from the source) and dropped into https://github.com/vasl-developers/vasl-boards-extensions/tree/master/boards and the version file updated, IIRC. Then Sam can put those board files into the zip files for vasl.info site.

**Comment by BigAl737** [comment]
Cool. I have already compiled them as bd files so that step is done. You can find a bdxx file in each of the bd folders in the vasl boards repository. I'm not sure how to drop them into the link you provide. I'll have to add that location to my SourceTree program I think. I'll see what I can learn about how to do that and push the compile bd and ovr files to the repository you provided the link for. I'll update the version txt file too. As you can tell, I'm not a programmer. I am treading in deep water here :-)  Thanks for the help!

**Comment by zgrose** [comment]
Ya, in broad brushstrokes: you check out that vasl-developers repo to your computer. Drop the board files into the right folder and then commit/push that change.

**Comment by derimmer** [comment]
Under Sully's tutelage, I will add the LOSData to 71, 72, and 73 and push them back up.

**Comment by BigAl737** [comment]
So it seems that we have a couple of folders for boards and overlays. To check my understanding...the boards folder within vasl is the primary source for all the files that are used to make each board and overlay. The board folder within vasl-boards-extensions is the primary repository for bd and ovr files that get posted to vasl.info by Sam. No need to respond unless I'm wrong.

**Comment by davidsullivan317** [comment]
Thanks again Allan and Scott for making the new boards a reality. 

I've tried to document the process to follow for creating and updating boards on the Wiki: https://github.com/vasl-developers/vasl/wiki/Updating-Boards-in-the-Age-of-Automatic-Board-Synchronization If it lacks clarity please flesh it out so it makes sense to you. 

It will be important to follow these steps once 6.3 is out as VASL will look to the vasl-boards-extensions repository to get the latest boards.

**Comment by styson** [comment]
I pushed the board and overlay updates, but the [version file](https://github.com/vasl-developers/vasl/blob/develop/boards/v5boardVersions.txt) has not been updated yet.

**Comment by BigAl737** [comment]
Just updated and pushed the version files

**Comment by BigAl737** [comment]
In addition, I updated bd10z and 17z to version 6.0 to match the other base version 6 boards

**Comment by BigAl737** [comment]
If I understand Sam correctly, bd71, bd72, bd73, ovrX, ovrOB, and ovrSt have been pushed to where they need to be for Sam to add them to vasl.info. I did update the version file for these boards and overlays. There is nothing else needed from me.

**Comment by derimmer** [comment]
There are files called v5boardVersions.txt and v5overlayVersions.txt which reside in the boards\src directory that need to be updated as well. I think that is what Sam was referring to by “the version file”.  When I added LOSData to 69 and 70, Sully had me update the v5boardVersions.txt file and push it up.

**Comment by derimmer** [comment]
Whoops! Missed your earlier message in which you said you had just done that! Sorry about that Alan. 

 

From: Doug Rimmer [mailto:dougrimmer@rogers.com] 
Sent: Friday, February 5, 2016 7:52 PM
To: 'vasl-developers/vasl-website' <reply@reply.github.com>; 'vasl-developers/vasl-website' <vasl-website@noreply.github.com>
Subject: RE: [vasl-website] AP11 stuff ready for the web site (#10)

 

There are files called v5boardVersions.txt and v5overlayVersions.txt which reside in the boards\src directory that need to be updated as well. I think that is what Sam was referring to by “the version file”.  When I added LOSData to 69 and 70, Sully had me update the v5boardVersions.txt file and push it up.

**Comment by BigAl737** [comment]
Hi David,

I checked out the process again and I don’t know how to use the board builder program. That seems sort of key.

I know you’re outta here for a while so we can follow up when you get back.

Al

**Comment by styson** [comment]
Version file processed and pushed to the web site.

**Comment by BigAl737** [comment]
> Version file processed and pushed to the web site.

Thank you Sam. I don't know how this process works so my apologies for pointing this out again but the newly created ovrOB, and updated ovrX and ovrST files are not part of the standard overlay zip file available for download on:
http://vasl.info/overlays.htm

You will find them here:
https://github.com/vasl-developers/vasl-boards-extensions/tree/master/boards/overlays

**Comment by derimmer** [comment]
I have attempted to flesh out the documentation and have opened a new issue for this.

**Comment by BigAl737** [comment]
Hi Doug,

Can you add what Sam has done to your documentation? I've pasted his instructions below. Thanks.

"I have changed the website to use the gh-pages branch as its content. If we can get that branch set as the default brach, then we can remove the master branch. At that point, any commits to the vasl-website repo will be live on the website. For board and overlay updates, that means that the new zip files can be dropped right into the boards and overlays folders. Any new boards, such as 74 & 75) would also need to be get links added to the board.htm folder."

**Comment by derimmer** [comment]
Will do!

**Comment by BigAl737** [comment]
Thanks Doug. That document will be very helpful. I'll close this issue now.

**Comment by derimmer** [comment]
Well, I may have been a bit too enthusiastic. . . . 

I am having some trouble actually understanding Sam’s text. I can easily edit my current instructions but I have not yet figured out how to say it.

You have obviously figured out what needs to be done. Could you describe in a couple of sentences what you did with the RB board? 

Thanks.

**Comment by BigAl737** [comment]
I will try to put something together soon but I am far from the expert. I’m probably screwing things up more than I’m helping.

When uploading bd40 I’ve been stumped by another issue.

Can anyone tell me how to update the little board version number that shows up on the Boards download page? Bd40 should say 6.1 but still says 6.0. It looks like the update should be automatic but I can’t tell where the version number gets it’s data from.

Thanks.

Allan

**Comment by styson** [comment]
Currently the versions are pulled from https://github.com/vasl-developers/vasl-website/blob/gh-pages/boards/versions.json. This file might be duplicated, but for now it is the source for the website. Changes made to the file take 5-10 minutes to propagate to vasl.info via github pages.

I updated the file for board 40.
