### ISSUE TITLE
Update BFP extension. 

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl-website#12]
available below

**Comment by BigAl737** [comment]
There's some clean up required with a couple of image files that I provided. I'll get those images corrected ASAP and let you know where you can get the updated BFP_v4 extension for upload and release to the masses.

**Comment by BigAl737** [comment]
Clean up is complete. Sam, please upload this version:
https://www.dropbox.com/s/7qmytfiwkeve5n4/BFP_v4.vmdx?dl=0

Again, great job everyone. The masses will really enjoy this.

Allan

**Comment by BigAl737** [comment]
Sam, the wrong file got uploaded. See the message above. Also, can you put my name in the credits. I did the counters and want people to know that any counter issues are mine, not Ken's. Thanks.

**Comment by BigAl737** [comment]
David, your link in the first post is not required any more. Can you delete it to avoid future confusion? Thanks.

**Comment by styson** [comment]
all of the v6 extensions are on the website as *.vmdx files. Any zipping of the file (if any) is controlled by the download process.

**Comment by BigAl737** [comment]
I hate computers :-)

Okay, now I understand. If I renamed the file downloaded from vasl.info with a vdmx extension, it seems to work just fine. And the graphics are updated as well.

Nice job. Time to play.

Al

**Comment by BigAl737** [comment]
Should we upload the source files for this extension? If so, I can do this if you'd point out the best place to put them.

**Comment by styson** [comment]
It seems like the source files should be held in GitHub. I think we should add an extensions folder in https://github.com/vasl-developers/vasl and start adding folders for each extension there, just like we do for boards.

**Comment by davidsullivan317** [comment]
Nefarious link removed. I second Sam's recommendation on managing the extension source.
