### ISSUE TITLE
version 6.6.9 release not tagged 

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl-website#123]
Open browser to vasl.info
Click "download" button on upper-right menu bar
Click "VASL 6.6.9"

Result: 404 error

The url the web site is trying to open is, "https://github.com/vasl-developers/vasl/releases/tag/vasl-6.6.9"

What I believe is the correct file, https://github.com/vasl-developers/vasl/releases/download/untagged-413f4735d06b47515a1a/vasl-6.6.9.vmod, is apparently not tagged properly.

**Comment by jrvjrv** [comment]
VASL 6.6.8 also has the same issue.

**Comment by jrvjrv** [comment]
There may be more than one issue here. There may be a security settings problem too? If you visit "https://github.com/vasl-developers/vasl/releases" without being logged into github, neither 6.6.9 nor 6.6.8 appear in the list of release downloads. If you visit while logged in, both are available for direct download.

**Comment by jrvjrv** [comment]
Problem is now semi-fixed. It turns out I have rights on the github repository. The 6.6.9 version was not "published," whatever that means to github. I published it. The link from vasl.info now takes you to a github page where you can download the .vmod even if not logged into github. It does not directly download the .vmod like 6.6.7 does, and I am going to leave that part of the fix to more knowledgeable persons. I did nothing to fix 6.6.8.

**Comment by uckelman** [comment]
A bunch of releases have been left as drafts. You have to click the "Publish Release" button on the editing page when editing to publish a release. It won't be visible to anyone who doesn't have edit privileges before that.

**Comment by geezer09** [comment]
Ok, we had some issues with tags, edited releases and links but I think everything is okay now. Let me know if you find other issues.

**Comment by jrvjrv** [comment]
It looks as though someone (re?) published 6.6.8, and publishing 6.6.9 was the right thing to do. Also the links have now been corrected to go directly to the .vmods. I am closing this issue now
