### ISSUE TITLE
AREA rating system

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl-website#55]
I have learned that the AREA website, run recently by Bruno Nitrosso has gone dormat. This site provides a player ranking system which is used by some tournaments to seed players. Results from VASL leagues are added to the system. 

These kinds of sites are often run by one person at a time and at some point life happens and the person is no longer willing or able to carry on. 

Would it be a good fit to add this to the VASL website? At least then the underlying code and tools would be easily accessible via GitHub and we might be able to push out the data input to Tournament Directors such that it would require less effort to manage. I have only a vague notion of how it has worked recently but would be happy to approach Bruno and get his thoughts about it.

What do you think?

**Comment by Javaslinger** [comment]
I think that's a great idea.  I would be willing to help with this effort.  I'm no coder, but I could potentially work on the administrative end once it is set up.
Thanks
Ken Sharp-Knott
    On Sunday, March 3, 2019, 10:17:37 AM EST, Doug Rimmer <notifications@github.com> wrote:  
 
 
I have learned that the AREA website, run recently by Bruno Nitrosso has gone dormat. This site provides a player ranking system which is used by some tournaments to seed players. Results from VASL leagues are added to the system.

These kinds of sites are often run by one person at a time and at some point life happens and the person is no longer willing or able to carry on.

Would it be a good fit to add this to the VASL website? At least then the underlying code and tools would be easily accessible via GitHub and we might be able to push out the data input to Tournament Directors such that it would require less effort to manage. I have only a vague notion of how it has worked recently but would be happy to approach Bruno and get his thoughts about it.

What do you think?

**Comment by hongkongwargamer** [comment]
Here’s the latest on this .. from about 4 hours ago.  

http://www.gamesquad.com/forums/index.php?threads/area-a-small-info.143586/#post-1966056

Warm regards, Jack 

—
hongkongwargamer.com 
Twitter @HWargamer
Discord: https://discord.gg/XxpxAvx
Signal+Slack, VASL 6.4.3

On 4 March 2019 at 00:12:00, Ken Sharp-Knott (notifications@github.com) wrote:

I think that's a great idea.  I would be willing to help with this effort.  I'm no coder, but I could potentially work on the administrative end once it is set up.
Thanks
Ken Sharp-Knott
On Sunday, March 3, 2019, 10:17:37 AM EST, Doug Rimmer <notifications@github.com> wrote:


I have learned that the AREA website, run recently by Bruno Nitrosso has gone dormat. This site provides a player ranking system which is used by some tournaments to seed players. Results from VASL leagues are added to the system.

These kinds of sites are often run by one person at a time and at some point life happens and the person is no longer willing or able to carry on.

Would it be a good fit to add this to the VASL website? At least then the underlying code and tools would be easily accessible via GitHub and we might be able to push out the data input to Tournament Directors such that it would require less effort to manage. I have only a vague notion of how it has worked recently but would be happy to approach Bruno and get his thoughts about it.

What do you think?

**Comment by zgrose** [comment]
BTW, if anyone wants to grab the database, I can host it in my Azure account so we can see what we're dealing with.

**Comment by derimmer** [comment]
I will be contacting Bruno today to see what's up and if we can get a copy of the db.

**Comment by derimmer** [comment]
Response from Bruno. He has cut and pasted his responses into my original email but I think you can decipher it.

Hi Doug

>I am part of the group that manages the VASL software.
OUaouh. That's a major asset for the community and an outstanding endeavour. Thanks to you and all the gang behind it.

>our thanks to you for all the hard work and time you have put into AREA over the years. 
It's been my pleasure and a way to give back since ASL and its community have given me so MANY hours of great fun.
:-)
SOME TEXT EDITED HERE BY BRUNO
> I wanted to ask you if you think this is feasible 

>and if you would be willing to have us take it on? 
I don't feel I have a word on the issue. Yet, my word is "Yes of course".

>We know nothing about the underlying code and database that are used. Could you give us some information about that?
1= Data and Database : 
    the MySQL data-base structure is super simple and I have the raw data in .csv text file and the table descriptions too.
    So, no problem for this. Around 3 000 players and 25,000 games

2= The code... Well it is a VERY VERY dirty Perl hack. I would be embarrased to show it to whom ever... But to the guys that do VASL is just overly embarrassing...
I can describe the modules which are :
    1= uploading data from simple .csv files
    2= computing ELO ratings
    3= generating HTML sheets and uploading them to asl-area.org site



>Our hope is that by integrating the AREA tool with the VASL website, we might be able to make it more sustainable over the long term. That would be our rationale for taking it on, but frankly, we won’t really know if that is a realistic goal until we understand the AREA tool in more detail.
Seems like a great idea.
I will wrote some more later on.


Best Regards,
-Bruno

**Comment by zgrose** [comment]
Sounds like an easy port. The best kind. :)
