### ISSUE TITLE
Website Cleanup

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl-website#91]
@styson and I have discussed updating the FAQ page of the website and Sam is going to do some work on it. 

I will load VASL6.6.2 to the modules page tomorrow, unless shit happens.

We current have modules going to back to 5.6 released June 2007 on that page! I think we can cut it off at 6.1 released April 2014 and will make that change shortly unless anyone objects. Github holds all release from 6.0.3 onwards.

**Comment by BigAl737** [comment]
The map and extension pages need some freshening as well. Are these on the to do list?

**Comment by derimmer** [comment]
Well there are now! I agree on the extensions page. What needs to be done on the map pages?

**Comment by BigAl737** [comment]
My opinion only... There's some cosmetic clean up of the column extensions on the HASL page. Also, there's probably some consolidation of all the RB, RO boards that could be done.

**Comment by styson** [comment]
I updated the FAQ page in April, and cleaned up the board pages in May.
Cleaned up the old VASL modules today.
